### ISSUE TITLE
0.3.0 is not on pypi.org

### ISSUE THREAD

**Issue by dvzrv** [ansible-community/molecule-docker#24]
Hi! I'm packaging molecule-docker for Arch Linux.
I would like to upgrade to 0.3.0, but unfortunately the sdist tarball is not on pypi.org and with a tarball from github I can not build due to setuptools_scm.

**Comment by greg-hellings** [comment]
There was a problem in the CD pipeline that I've already addressed (hopefully). Look for 0.3.2 to arrive on PyPI in a few minutes if the CD runs through this time

**Comment by MarkusTeufelberger** [comment]
https://pypi.org/project/molecule-docker/#history - still not visible for me as of now.

**Comment by ssbarnea** [comment]
```
12:29 <Not-8188> [molecule-docker] ssbarnea opened pull request #26: Assure ansible has docker module - https://git.io/JTDUc
12:43 <Not-8188> [molecule-docker] ssbarnea pushed 1 commit [+0/-0/±2] https://git.io/JTDkZ
12:43 <Not-8188> [molecule-docker] ssbarnea 4b6e677 - Assure ansible has docker_container module installed (#26)
12:44 <Not-8188> [molecule-docker] ssbarnea published 0.3.3a1 | 0.3.3a1 - https://git.io/JTDkW
12:44 <Not-8188> [molecule-docker] ssbarnea tagged 4b6e677 as 0.3.3a1 https://git.io/JTDkl
13:30 <Not-8188> [molecule-docker] ssbarnea tagged 4b6e677 as 0.3.3 https://git.io/JTDkl
13:33 <zbr> i think this concludes that github release events are not to be trusted, i edited 0.3.3a1 prerelease and made it 0.3.3 release but it only produces a tag event
````

Probably the original implementation that only looked at tags is more was more reliable.

**Comment by greg-hellings** [comment]
The older one that relied on tags is prone to numerous issues, such as creating a release that's based on an already existing tag, the use of tags for things other than release, and the fact that Github appears to have changed the behavior of it.

The newer code specifically calls out at the top that it fires when a release is "published". Edited isn't included. If you want to be able to edit an alpha release into a final, just add "edited" to that list. I would think you'd want to cut a new one, but that's just my personal preference.

**Comment by ssbarnea** [comment]
I use edited because otherwise we pollute the releases pages with multiple releases that have no differences between them. Without having edit working we force release "manager" to perform copy/paste of release notes from previous release.

I think is perfectly normal to edit a release when transforming it from unreleased to pre-release, or from pre-release to release.

Still, it would be ugly to see a failed release pipeline if we decide to only edit the release notes on, without touching tags. Probably we need a check: if the same version was already released, skip it instead of failing to upload it.

**Comment by greg-hellings** [comment]
I have no idea how to check if PyPI already has release artefacts matching a given version. The only check I've ever seen is getting a 404 when trying to release with twine or whatever other tool.

**Comment by dvzrv** [comment]
Hm, this is rather unfortunate, as 0.3.3 of course orders before 0.3.3a1 ;-)

Well, I guess I'll use the 0.3.3a1 tarball there then.

**Comment by ssbarnea** [comment]
0.3.3 is now published.
